# Generated by Django 2.2 on 2019-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('reservation_information', models.CharField(max_length=1000)),
                ('ticket_available_date', models.DateTimeField(verbose_name='ticke available date')),
                ('date', models.DateTimeField(verbose_name='live date')),
            ],
        ),
    ]
