# Generated by Django 2.2 on 2019-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
