# Generated by Django 2.2 on 2019-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_info', '0002_live_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='live',
            name='member',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='live',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='live',
            name='ticket_available_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
